### ISSUE TITLE
Add Download video button next to clear all or below captions

### ISSUE THREAD

**Issue by drnitinp** [drnitinp/videocaptionsearch#24]

**Comment by rajch** [comment]
This is not practically possible, as all browsers prevent javascript/HTML-initiated downloads for videos which come from a remote site. The only way is for the user to take a browser-level action, such as right-clicking the video and choosing "Save video as..." or clicking the download button on the video.

The download button seems to be available only on chrome, so I have included the right-click instructions on screen.

![image](https://user-images.githubusercontent.com/11015097/69473951-6960ac00-0de0-11ea-8348-52ae493124f3.png)
