### ISSUE TITLE
align top = start time and end time buttons 

### ISSUE THREAD

**Issue by drnitinp** [drnitinp/videocaptionsearch#25]
![image](https://user-images.githubusercontent.com/16194339/69451456-66849d80-0d85-11ea-82a1-4e0b5f87045f.png)
1 - Add title here. Left aligned. With fixed space of 14 px from the Start time. On resize, it should get truncated and be BEHIND the end time
1, 2 and 3 must be top aligned
4 - add download button. Svg for download uploaded to assets

**Comment by rajch** [comment]
This seems unwieldy. Title is not highlighted, and is distracting where it is. 

Also, download is not practically possible. Refer #24 .

I propose an alternative design, with a title strip in the middle which can also show download instructions. A draft is shown here:

![image](https://user-images.githubusercontent.com/11015097/69473951-6960ac00-0de0-11ea-8348-52ae493124f3.png)
